version: '2'
services:
  kafkabroker:
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      - --advertise-kafka-addr
      - PLAINTEXT://kafkabroker:9092,OUTSIDE://localhost:29092
    image: docker.vectorized.io/vectorized/redpanda:latest
    container_name: kafkabroker
    ports:
      - 9092:9092
      - 29092:29092
    networks:
      - kafkaNet
      - mainNet
      - playerNet

networks:
  kafkaNet:
    external: true
  mainNet:
    external: true
  playerNet:
    external: true
